#!/bin/bash

# 🚀 Deploy Manual - OMúsicoCatólico
# Script para deploy das melhorias CSS

echo "🎨 Deploy das Melhorias CSS - OMúsicoCatólico"
echo "=============================================="

# Variáveis
SERVER_IP="142.93.55.152"
SERVER_USER="root"
PROJECT_PATH="/var/www/omusicacatolico"

echo ""
echo "📋 INSTRUÇÕES DE DEPLOY MANUAL:"
echo ""
echo "1️⃣ Conecte ao servidor via SSH:"
echo "   ssh root@$SERVER_IP"
echo "   (Senha: OMusicoCatolico2025p)"
echo ""
echo "2️⃣ Execute os comandos abaixo no servidor:"
echo ""
echo "# Navegar para o projeto"
echo "cd $PROJECT_PATH"
echo ""
echo "# Fazer backup dos arquivos atuais"
echo "cp -r frontend/css frontend/css.backup-$(date +%Y%m%d)"
echo ""
echo "# Atualizar código"
echo "git pull origin main"
echo ""
echo "# Verificar se os novos arquivos CSS estão presentes"
echo "ls -la frontend/css/"
echo ""
echo "# Reinstalar dependências se necessário"
echo "npm install --production"
echo ""
echo "# Reiniciar aplicação"
echo "pm2 restart omusicacatolico"
echo ""
echo "# Verificar status"
echo "pm2 status"
echo "pm2 logs omusicacatolico --lines 10"
echo ""
echo "3️⃣ Testar o site:"
echo "   https://omusicocatolico.com.br"
echo ""
echo "✅ Arquivos CSS implementados:"
echo "   - frontend/css/design-system.css (Variáveis e tokens)"
echo "   - frontend/css/components.css (Componentes reutilizáveis)"
echo "   - frontend/css/main.css (Arquivo principal)"
echo "   - frontend/css/responsive.css (Sistema responsivo)"
echo "   - frontend/index.html (Página atualizada)"
echo ""
echo "🎯 BENEFÍCIOS DAS MELHORIAS:"
echo "   ✅ Sistema de design profissional"
echo "   ✅ Componentes reutilizáveis"
echo "   ✅ Responsividade otimizada"
echo "   ✅ Performance melhorada"
echo "   ✅ Manutenção simplificada"
echo ""
echo "📞 Em caso de problemas:"
echo "   - Verifique logs: pm2 logs omusicacatolico"
echo "   - Restart: pm2 restart omusicacatolico"
echo "   - Status: pm2 status"
echo "   - Rollback: git checkout HEAD~1 (se necessário)"
echo ""
echo "🎉 O sistema CSS está pronto para produção!" 