#!/bin/bash

echo "🔍 Diagnóstico SSH - OMúsicoCatólico"
echo "==================================="

SERVER="142.93.55.152"

echo ""
echo "1. Testando conectividade básica..."
ping -c 2 $SERVER

echo ""
echo "2. Testando porta SSH..."
nc -zv $SERVER 22

echo ""
echo "3. Tentativas de conexão SSH:"
echo ""

echo "📝 MÉTODOS PARA TENTAR:"
echo ""
echo "Método 1 - SSH padrão:"
echo "ssh root@$SERVER"
echo ""
echo "Método 2 - SSH com força de senha:"
echo "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no root@$SERVER"
echo ""
echo "Método 3 - SSH com timeout maior:"
echo "ssh -o ConnectTimeout=30 root@$SERVER"
echo ""
echo "Método 4 - Tentar com usuário diferente:"
echo "ssh ubuntu@$SERVER"
echo "ssh admin@$SERVER"
echo ""
echo "🔧 ALTERNATIVAS SE SSH NÃO FUNCIONAR:"
echo ""
echo "1. 🌐 Console Web do Digital Ocean:"
echo "   - Acesse o painel do Digital Ocean"
echo "   - Clique no seu Droplet"
echo "   - Use o botão 'Console' para acesso direto"
echo ""
echo "2. 📱 App móvel Digital Ocean:"
echo "   - Use o app para acessar o console"
echo ""
echo "3. 🔑 Configurar chave SSH:"
echo "   - ssh-keygen -t rsa"
echo "   - Adicionar chave ao Digital Ocean"
echo ""
echo "📋 COMANDOS PARA EXECUTAR NO SERVIDOR:"
echo "(Execute estes comandos quando conseguir acesso)"
echo ""
echo "cd /var/www/omusicacatolico"
echo "git pull origin main"
echo "npm install --production"
echo "pm2 restart omusicacatolico"
echo "pm2 status"
echo ""
echo "✅ Teste final: https://omusicocatolico.com.br" 